export const INITIALIZE_CHART_DATA = 'INITIALIZE_CHART_DATA';
export const GENERATE_NEW_ARRAY = 'GENERATE_NEW_ARRAY';
export const SET_IS_NAVBAR_CLICKABLE = 'SET_IS_NAVBAR_CLICKABLE';
export const BAR_CHART_DEFAULT_BACKGROUND_COLOR = 'rgba(255,99,132,0.2)';
