export const INITIALIZE_CHART_DATA = 'INITIALIZE_CHART_DATA';
export const GENERATE_NEW_ARRAY = 'GENERATE_NEW_ARRAY';
export const SET_IS_NAVBAR_CLICKABLE = 'SET_IS_NAVBAR_CLICKABLE';

export const BAR_CHART_DEFAULT_BACKGROUND_COLOR = 'rgba(255,99,132,0.2)';
export const MARKED_ELEMENT_BACKGROUND_COLOR = 'yellow';

export const SET_BAR_CHART_ELEMENT_BACKGROUND_COLOR =
  'SET_BAR_CHART_ELEMENT_BACKGROUND_COLOR';

export const SET_TOTAL_SWAPS = 'SET_TOTAL_SWAPS';
export const TOTAL_SWAPS_DEFAULT_VALUE = 0;
